#!/bin/sh

set -o nounset

function stash {
    git stash -q --keep-index
}
function unstash {
    git stash pop -q
}

stash
trap unstash EXIT

./script/test > /dev/null 2>&1

readonly EXIT=$?

if [[ $EXIT -ne 0 ]]; then
    echo "Cannot commit, there are failing tests.\n"
    exit 1
else
    exit 0
fi

